### ISSUE TITLE
Encode and Decode long header packet length

### ISSUE THREAD

**Issue by davisouzaluna** [davifurao/Dquic#1]
Is necessary to create a logical function to implements the encoding and decoding decimal numbers(will be represent the length packet) to bit. The information about is on RFC 9000(QUIC Version 1). The section is 16([Variable-Length Integer Encoding](https://datatracker.ietf.org/doc/html/rfc9000#name-variable-length-integer-enc)). The function will be implement in the constructor packet handshake(setup functions) in packet.c file to modify the header struct.

**Comment by davifurao** [comment]
Initial version is published in 47c1bf332d8047e8046460fb8f4de30ae69566c9 commit. I used chat GPT when I study. It's necessary a review
